name: Vitest/Playwright testing
on:
  [push, pull_request]
  #workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run ESLint
        id: eslint
        # Allow error to generate the 'FAIL' badge below
        continue-on-error: true
        run: npm run lint

      - name: Generate ESLint Badge
        run: |
          mkdir -p .github/badges
          OUTCOME="${{ steps.eslint.outcome }}"
          COLOR="red"
          MESSAGE="FAIL"

          if [ "$OUTCOME" == "success" ]; then
            COLOR="266429"
            MESSAGE="PASS"
          fi

          echo "Generating ESLint badge: Status=$MESSAGE"

          curl -s -G "https://img.shields.io/badge/ESLint-$MESSAGE-$COLOR" \
          -d style=flat \
          -d logo=eslint \
          -d logoColor=%234B32C3 \
          > .github/badges/eslint.svg

          if ! grep -q "^<svg" .github/badges/vitest.svg; then
            echo "âŒ Error: Downloaded file is not a valid SVG."
            cat .github/badges/vitest.svg
            exit 1
          fi

      # Vitest
      - name: Run Vitest
        id: vitest
        # Allow error to generate the 'FAIL' badge below
        continue-on-error: true
        run: npm run test:unit

      - name: Generate Vitest Badge
        run: |
          mkdir -p .github/badges

          # Check outcome of the previous step
          OUTCOME="${{ steps.vitest.outcome }}"

          COLOR="red"
          MESSAGE="FAIL"

          if [ "$OUTCOME" == "success" ]; then
            COLOR="266429" 
            MESSAGE="PASS"
          fi

          echo "Generating Vitest badge: Status=$MESSAGE"

          curl -s -G "https://img.shields.io/badge/Vitest-$MESSAGE-$COLOR" \
            -d style=flat \
            -d logo=vitest \
            -d logoColor=%236E9F18 \
            -d labelColor=%23F0F0F0 \
            > .github/badges/vitest.svg

          # Verify that the file starts with `<svg`
          if ! grep -q "^<svg" .github/badges/vitest.svg; then
            echo "âŒ Error: Downloaded file is not a valid SVG."
            cat .github/badges/vitest.svg
            exit 1
          fi

      # PlayWrihgt
      - name: Run Playwright
        id: playwright
        # Allow error to generate the 'FAIL' badge below
        continue-on-error: true
        env:
          SECRET_RESEND_API_KEY: ${{ secrets.SECRET_RESEND_API_KEY }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        run: npm run test:e2e

      - name: Generate Playwright Badge
        run: |
          OUTCOME="${{ steps.playwright.outcome }}"

          COLOR="red"
          MESSAGE="FAIL"

          if [ "$OUTCOME" == "success" ]; then
            COLOR="266429"
            MESSAGE="PASS"
          fi

          # DEBUG: Print what we are about to request
          echo "Generating badge: Status=$MESSAGE, Color=$COLOR"

          # Download the Badge as an SVG
          curl "https://img.shields.io/badge/Playwright-$MESSAGE-$COLOR?style=flat&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgd2lkdGg9IjI0IgogICBoZWlnaHQ9IjI0IgogICBmaWxsPSJub25lIgogICB2ZXJzaW9uPSIxLjEiCiAgIGlkPSJzdmc0IgogICB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxkZWZzCiAgICAgaWQ9ImRlZnM0IiAvPgogIDxwYXRoCiAgICAgZmlsbD0iI2UyNTc0YyIKICAgICBkPSJtIDkuNzEzLDE1LjkxNSB2IC0xLjUyNyBsIC00LjI0NCwxLjIwMyBjIDAsMCAwLjMxNCwtMS44MjIgMi41MjcsLTIuNDUgMC42NzEsLTAuMTkgMS4yNDQsLTAuMTg4IDEuNzE3LC0wLjA5NyBWIDYuNzggaCAyLjEyNCBBIDEyLjcyNywxMi43MjcgMCAwIDAgMTEuMTk0LDUuMTMzIEMgMTAuODg0LDQuNSAxMC41NjQsNC45MTkgOS44NDEsNS41MjQgOS4zMzEsNS45NSA4LjA0Myw2Ljg1OCA2LjEwNSw3LjM4MSA0LjE2Nyw3LjkwMyAyLjYsNy43NjUgMS45NDUsNy42NTEgMS4wMTksNy40OTEgMC41MzUsNy4yODggMC41OCw3Ljk5MyBjIDAuMDM5LDAuNjIyIDAuMTg3LDEuNTg2IDAuNTI2LDIuODYgMC43MzUsMi43NTcgMy4xNiw4LjA3IDcuNzQ1LDYuODM1IDEuMTk4LC0wLjMyMiAyLjA0MywtMC45NiAyLjYzLC0xLjc3MyBIIDkuNzEyIFogTSAyLjg2NiwxMC44OSA2LjEyNCwxMC4wMzIgYyAwLDAgLTAuMDk1LDEuMjUzIC0xLjMxNywxLjU3NSBDIDMuNTg2LDExLjkyOSAyLjg2NiwxMC44OSAyLjg2NiwxMC44OSBaIgogICAgIGlkPSJwYXRoMSIgLz4KICA8cGF0aAogICAgIGZpbGw9IiMyZWFkMzMiCiAgICAgZD0iTSAyMS45NzUsNi44NTMgQyAyMS4xMjgsNy4wMDEgMTkuMDk2LDcuMTg2IDE2LjU4NSw2LjUxMyAxNC4wNzMsNS44NCAxMi40MDcsNC42NjMgMTEuNzQ2LDQuMTExIDEwLjgxLDMuMzI3IDEwLjM5OSwyLjc4MSA5Ljk5NCwzLjYwNiA5LjYzNSw0LjMzMyA5LjE3Nyw1LjUxNiA4LjczNCw3LjE3MiBjIC0wLjk2LDMuNTg2IC0xLjY3OSwxMS4xNTQgNC4yNiwxMi43NDYgNS45MzgsMS41OTEgOS4xLC01LjMyMiAxMC4wNiwtOC45MDggMC40NDQsLTEuNjU2IDAuNjM4LC0yLjkxIDAuNjkyLC0zLjcxOCAwLjA2MSwtMC45MTYgLTAuNTY4LC0wLjY1IC0xLjc3LC0wLjQ0IHogTSAxMC4wNDIsOS44MTkgYyAwLDAgMC45MzYsLTEuNDU1IDIuNTIzLC0xLjAwNCAxLjU4OSwwLjQ1MSAxLjcxMiwyLjIwNyAxLjcxMiwyLjIwNyBMIDEwLjA0Miw5LjgyIFogbSAzLjg3NSw2LjUzMyBjIC0yLjc5MiwtMC44MTggLTMuMjIzLC0zLjA0NSAtMy4yMjMsLTMuMDQ1IGwgNy41MDEsMi4wOTggYyAwLDAgLTEuNTE0LDEuNzU1IC00LjI3OCwwLjk0NyB6IG0gMi42NTIsLTQuNTc2IGMgMCwwIDAuOTM1LC0xLjQ1NSAyLjUyMiwtMS4wMDIgMS41ODcsMC40NTIgMS43MTIsMi4yMDggMS43MTIsMi4yMDggeiIKICAgICBpZD0icGF0aDIiIC8+CiAgPHBhdGgKICAgICBmaWxsPSIjMmVhZDMzIgogICAgIGQ9Im0gMTQuMDQzLDE2LjM4MyAtMC4xMjYsLTAuMDMxIGMgLTIuNzkzLC0wLjgxOCAtMy4yMjMsLTMuMDQ1IC0zLjIyMywtMy4wNDUgbCAzLjg2OCwxLjA4MiAyLjA0OCwtNy44NyAtMC4wMjUsLTAuMDA2IEMgMTQuMDczLDUuODQgMTIuNDA2LDQuNjYzIDExLjc0Niw0LjExMSAxMC44MSwzLjMyNyAxMC4zOTgsMi43ODEgOS45OTMsMy42MDYgOS42MzUsNC4zMzMgOS4xNzcsNS41MTYgOC43MzMsNy4xNzIgNy43NzMsMTAuNzU4IDcuMDU1LDE4LjMyNiAxMi45OTQsMTkuOTE4IGwgMC4xMjIsMC4wMjggeiBNIDEwLjA0Miw5LjgxOSBjIDAsMCAwLjkzNiwtMS40NTUgMi41MjMsLTEuMDA0IDEuNTg5LDAuNDUxIDEuNzEyLDIuMjA3IDEuNzEyLDIuMjA3IEwgMTAuMDQyLDkuODIgWiIKICAgICBpZD0icGF0aDQiIC8+Cjwvc3ZnPgo=&labelColor=%23F0F0F0" > .github/badges/playwright.svg

          # Verify that the file starts with `<svg`
          if ! grep -q "^<svg" .github/badges/playwright.svg; then
            echo "âŒ Error: Downloaded file is not a valid SVG."
            cat .github/badges/playwrigth.svg
            exit 1
          fi

      # Commit badges / fail
      - name: Commit Badges
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ðŸ¤– Update Testing Badges [skip ci]"
          file_pattern: .github/badges/*.svg

      - name: Upload Report on Failure
        if: steps.playwright.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5

      - name: Check for Failures
        if: steps.eslint.outcome == 'failure' || steps.vitest.outcome == 'failure' || steps.playwright.outcome == 'failure'
        run: |
          echo "âŒ One or more tests failed."
          exit 1
